name: Auto Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required to check previous tags

      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          VERSION=$(grep '^version =' Cargo.toml | awk -F '"' '{print $2}')
          echo "VERSION=v$VERSION" >> $GITHUB_ENV
          echo "Detected version: v$VERSION"

      - name: Check if tag already exists
        id: check_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view ${{ env.VERSION }} >/dev/null 2>&1; then
            echo "Release ${{ env.VERSION }} already exists. Skipping."
            echo "EXISTS=true" >> $GITHUB_ENV
          else
            echo "EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create Release
        if: env.EXISTS == 'false'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
